[build]
  command = "hugo"
  publish = "public"

[build.environment]
  HUGO_VERSION = "0.117.0"
  HUGO_BASEURL = "https://zojump.com"

[context.production.environment]
  HUGO_ENV = "production"

[context.deploy-preview.environment]
  HUGO_BASEURL = "/"
